=== petr7555/PB029-Contacts-XML-to-HTML-transformation/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="contacts">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="contact" type="contact-type"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="contact-type">
        <xs:all>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="contact-info" type="contact-info-type"/>   
			<xs:element name="notes" type="notes-type"/>            
        </xs:all>
    </xs:complexType>
    
    <xs:complexType  name="contact-info-type">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="email" type="email-type"/>
	            <xs:element name="phone-number" type="phone-number-type"/>
	            <xs:element name="link" type="link-type"/>
	            <xs:element name="other" type="other-type"/>
	            <xs:element name="address" type="address-type"/>
            </xs:choice>
    </xs:complexType>
    
    <xs:simpleType name="restricted-email-type">
      <xs:restriction base="xs:string">
        <xs:pattern value="\S+@\S+\.\S+"/>
      </xs:restriction>
    </xs:simpleType>
        
    <xs:complexType name="email-type">
        <xs:simpleContent>
		<xs:extension base="restricted-email-type">
		  <xs:attribute name="purpose" type="purpose-type"/> 
		</xs:extension>
        </xs:simpleContent>
    </xs:complexType>
            
    <xs:simpleType name="restricted-phone-number-type">
      <xs:restriction base="xs:string">
        <xs:pattern value="[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="phone-number-type">
        <xs:simpleContent>
			<xs:extension base="restricted-phone-number-type">
			  <xs:attribute name="purpose" type="purpose-type"/> 
			</xs:extension>
        </xs:simpleContent>
    </xs:complexType>  
    
    <xs:complexType name="link-type">
        <xs:simpleContent>
		<xs:extension base="xs:string">
		  <xs:attribute name="purpose" type="purpose-type"/> 
		</xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="purpose-type">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="personal" />
	    <xs:enumeration value="work" />
	    <xs:enumeration value="other" />
	  </xs:restriction>
	</xs:simpleType>
	
    <xs:complexType name="other-type">
        <xs:all>
            <xs:element name="name" type="name-type"/>
            <xs:element name="id" type="id-type"/> 
        </xs:all>
    </xs:complexType>
    
    <xs:simpleType name="name-type">
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z0-9]+"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="id-type">
      <xs:restriction base="xs:string">
        <xs:pattern value="[ A-Za-z0-9_@./&amp;#+-]+"/>
      </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="address-type">
        <xs:all>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="house-number" type="xs:string"/>
            <xs:element name="postcode" type="xs:string"/>            
        </xs:all>
    </xs:complexType>  
    
    <xs:complexType  name="notes-type">
	    <xs:choice minOccurs="0" maxOccurs="unbounded">
	        <xs:element name="note" type="xs:string"/>
	    </xs:choice>
    </xs:complexType>
</xs:schema>

=== petr7555/PB029-Contacts-XML-to-HTML-transformation/valid-full-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">
    <contact>
        <firstname>John</firstname>
        <lastname>Doe</lastname>
        <contact-info>
        	<email>john@nopurpose.com</email>
        	<email purpose="personal">john@home.com</email>
	        <email purpose="work">john@work.com</email>
	        <email purpose="work">john@work2.com</email>
	        <email purpose="other">john@spaghetti.com</email>
	        
	        <phone-number>123456789</phone-number>
	        <phone-number purpose="personal">+(123)-456-78-90</phone-number>
	        <phone-number purpose="work">123-1</phone-number>
	        <phone-number purpose="work">123-2</phone-number>
	        <phone-number purpose="other">+420602123456</phone-number>
	        
	        <link>http://www.john-nopurpose.com</link>
	        <link purpose="personal">http://www.john-home.com</link>
	        <link purpose="work">http://www.john-work.com</link>
	        <link purpose="work">http://www.john-work2.com</link>
	        <link purpose="other">http://www.john-spaghetti.com</link>
	        
	        <other>
				<name>Skype2021</name>
				<id>john.doe-1234</id>
			</other>
			
			<other>
				<name>Twitter</name>
				<id>@john&amp;1234</id>
			</other>
			
			<address>
				<city>London</city>
				<street>First avenue</street>
				<house-number>1004/17</house-number>
				<postcode>17800</postcode>
			</address>
			
			<address>
				<city>Brno</city>
				<street>Brněnská avenue</street>
				<house-number>897</house-number>
				<postcode>602 00</postcode>
			</address>			
		</contact-info>
		
		<notes>
			<note>
			Sweet roll croissant candy lollipop chupa chups toffee. 
			Chocolate cake sugar plum ice cream candy sweet sweet marzipan. 
			Tiramisu chocolate bar dessert carrot cake. Chocolate apple pie jelly gingerbread tootsie roll jujubes. 
			Halvah croissant pudding macaroon soufflé chocolate bar. Dragée topping soufflé lemon drops cake. 
			Brownie sweet roll sweet icing brownie muffin caramels carrot cake sesame snaps. Apple pie lollipop jelly tiramisu. 
			Powder cake sweet roll. Biscuit gummi bears bear claw chocolate candy chocolate bar brownie. 
			Candy gummies biscuit soufflé soufflé bonbon caramels liquorice sesame snaps. 
			Gummies bonbon croissant lollipop jelly muffin tootsie roll ice cream. 
			Topping cheesecake chocolate pie wafer bear claw marzipan. Liquorice sesame snaps cake sugar plum powder carrot cake croissant bear claw.
			</note>
			
			<note>
			Bacon ipsum dolor amet burgdoggen chuck chicken drumstick ribeye meatloaf chislic corned beef short ribs tri-tip. 
			Tenderloin porchetta pork belly filet mignon chicken bacon. Ball tip leberkas pork chop, 
			turkey kevin ham hock ground round bresaola. Hamburger porchetta ham hock pork belly turducken 
			tri-tip andouille pork burgdoggen leberkas pancetta tail kevin landjaeger.
			</note>
		</notes>
    </contact>
</contacts>

=== petr7555/PB029-Contacts-XML-to-HTML-transformation/valid-real-world-records.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">
    <contact>
        <firstname>John</firstname>
        <lastname>Doe</lastname>
        <email>john@doe.com</email>
        <phone-number>123456789</phone-number>
        <link>0</link>
    </contact>
    <contact>
        <firstname>John</firstname>
        <lastname>Doe</lastname>
        <email>john@doe.com</email>
        <phone-number>123456789</phone-number>
        <link>0</link>
    </contact>
    <contact>
        <firstname>John</firstname>
        <lastname>Doe</lastname>
        <email>john@doe.com</email>
        <phone-number>123456789</phone-number>
        <link>0</link>
    </contact>
</contacts>
